<?php
/**
 * Plurinational State of Bolivia states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-19
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'BO' => [
		'BO' => __( 'Bolivar', 'ry-wc-city-select' ),
		'CA' => __( 'Caranavi', 'ry-wc-city-select' ),
		'ENBA' => __( 'Enrique Baldivieso', 'ry-wc-city-select' ),
		'GEBU' => __( 'German Busch', 'ry-wc-city-select' ),
		'GU' => __( 'Guarayos', 'ry-wc-city-select' ),
		'JOMAPA' => __( 'Jose Manuel Pando', 'ry-wc-city-select' ),
		'LIAT' => __( 'Litoral de Atacama', 'ry-wc-city-select' ),
		'NOCAPR' => __( 'Nor Carangas Province', 'ry-wc-city-select' ),
		'PRAB' => __( 'Provincia Abuna', 'ry-wc-city-select' ),
		'PRALIB' => __( 'Provincia Alonzo de Ibanez', 'ry-wc-city-select' ),
		'PRANIB' => __( 'Provincia Andres Ibanez', 'ry-wc-city-select' ),
		'PRANSA' => __( 'Provincia Angel Sandoval', 'ry-wc-city-select' ),
		'PRAR' => __( 'Provincia Arani', 'ry-wc-city-select' ),
		'PRAR2' => __( 'Provincia Arce', 'ry-wc-city-select' ),
		'PRAR3' => __( 'Provincia Aroma', 'ry-wc-city-select' ),
		'PRAR4' => __( 'Provincia Arque', 'ry-wc-city-select' ),
		'PRAV' => __( 'Provincia Avaroa', 'ry-wc-city-select' ),
		'PRAV2' => __( 'Provincia Avilez', 'ry-wc-city-select' ),
		'PRAY' => __( 'Provincia Ayopaya', 'ry-wc-city-select' ),
		'PRAZ' => __( 'Provincia Azurduy', 'ry-wc-city-select' ),
		'PRBASA' => __( 'Provincia Bautista Saavedra', 'ry-wc-city-select' ),
		'PRBEBO' => __( 'Provincia Belisario Boeto', 'ry-wc-city-select' ),
		'PRCA' => __( 'Provincia Camacho', 'ry-wc-city-select' ),
		'PRCA2' => __( 'Provincia Campero', 'ry-wc-city-select' ),
		'PRCA3' => __( 'Provincia Capinota', 'ry-wc-city-select' ),
		'PRCA4' => __( 'Provincia Carangas', 'ry-wc-city-select' ),
		'PRCA5' => __( 'Provincia Carrasco', 'ry-wc-city-select' ),
		'PRCE' => __( 'Provincia Cercado', 'ry-wc-city-select' ),
		'PRCH' => __( 'Provincia Chapare', 'ry-wc-city-select' ),
		'PRCH2' => __( 'Provincia Charcas', 'ry-wc-city-select' ),
		'PRCH3' => __( 'Provincia Chayanta', 'ry-wc-city-select' ),
		'PRCH4' => __( 'Provincia Chiquitos', 'ry-wc-city-select' ),
		'PRCO' => __( 'Provincia Cordillera', 'ry-wc-city-select' ),
		'PRDACA' => __( 'Provincia Daniel Campos', 'ry-wc-city-select' ),
		'PRESAR' => __( 'Provincia Esteban Arce', 'ry-wc-city-select' ),
		'PRFL' => __( 'Provincia Florida', 'ry-wc-city-select' ),
		'PRFRTA' => __( 'Provincia Franz Tamayo', 'ry-wc-city-select' ),
		'PRGEBI' => __( 'Provincia General Bilbao', 'ry-wc-city-select' ),
		'PRGEFERO' => __( 'Provincia General Federico Roman', 'ry-wc-city-select' ),
		'PRGEJOBA' => __( 'Provincia General Jose Ballivian', 'ry-wc-city-select' ),
		'PRGEJO' => __( 'Provincia German Jordan', 'ry-wc-city-select' ),
		'PRGRCH' => __( 'Provincia Gran Chaco', 'ry-wc-city-select' ),
		'PRGUVI' => __( 'Provincia Gualberto Villarroel', 'ry-wc-city-select' ),
		'PRHESI' => __( 'Provincia Hernando Siles', 'ry-wc-city-select' ),
		'PRIC' => __( 'Provincia Ichilo', 'ry-wc-city-select' ),
		'PRIN' => __( 'Provincia Ingavi', 'ry-wc-city-select' ),
		'PRIN2' => __( 'Provincia Inquisivi', 'ry-wc-city-select' ),
		'PRIT' => __( 'Provincia Itenez', 'ry-wc-city-select' ),
		'PRIT2' => __( 'Provincia Iturralde', 'ry-wc-city-select' ),
		'PRLACA' => __( 'Provincia Ladislao Cabrera', 'ry-wc-city-select' ),
		'PRLA' => __( 'Provincia Larecaja', 'ry-wc-city-select' ),
		'PRLI' => __( 'Provincia Linares', 'ry-wc-city-select' ),
		'PRLO' => __( 'Provincia Loayza', 'ry-wc-city-select' ),
		'PRLOAN' => __( 'Provincia Los Andes', 'ry-wc-city-select' ),
		'PRLUCA' => __( 'Provincia Luis Calvo', 'ry-wc-city-select' ),
		'PRMADI' => __( 'Provincia Madre de Dios', 'ry-wc-city-select' ),
		'PRMA' => __( 'Provincia Mamore', 'ry-wc-city-select' ),
		'PRMAKA' => __( 'Provincia Manco Kapac', 'ry-wc-city-select' ),
		'PRMAMACA' => __( 'Provincia Manuel Maria Caballero', 'ry-wc-city-select' ),
		'PRMA2' => __( 'Provincia Manuripi', 'ry-wc-city-select' ),
		'PRMA3' => __( 'Provincia Marban', 'ry-wc-city-select' ),
		'PRME' => __( 'Provincia Mendez', 'ry-wc-city-select' ),
		'PRMI' => __( 'Provincia Mizque', 'ry-wc-city-select' ),
		'PRMOOM' => __( 'Provincia Modesto Omiste', 'ry-wc-city-select' ),
		'PRMO' => __( 'Provincia Moxos', 'ry-wc-city-select' ),
		'PRMU' => __( 'Provincia Munecas', 'ry-wc-city-select' ),
		'PRMU2' => __( 'Provincia Murillo', 'ry-wc-city-select' ),
		'PRNISU' => __( 'Provincia Nicolas Suarez', 'ry-wc-city-select' ),
		'PRNOCH' => __( 'Provincia Nor Chichas', 'ry-wc-city-select' ),
		'PRNOCI' => __( 'Provincia Nor Cinti', 'ry-wc-city-select' ),
		'PRNOLI' => __( 'Provincia Nor Lipez', 'ry-wc-city-select' ),
		'PRNOYU' => __( 'Provincia Nor Yungas', 'ry-wc-city-select' ),
		'PRNUCH' => __( 'Provincia Nuflo de Chavez', 'ry-wc-city-select' ),
		'PROC' => __( 'Provincia OConnor', 'ry-wc-city-select' ),
		'PROM' => __( 'Provincia Omasuyos', 'ry-wc-city-select' ),
		'PROR' => __( 'Provincia Oropeza', 'ry-wc-city-select' ),
		'PRPA' => __( 'Provincia Pacajes', 'ry-wc-city-select' ),
		'PRPADA' => __( 'Provincia Pantaleon Dalence', 'ry-wc-city-select' ),
		'PRPO' => __( 'Provincia Poopo', 'ry-wc-city-select' ),
		'PRPU' => __( 'Provincia Punata', 'ry-wc-city-select' ),
		'PRQU' => __( 'Provincia Quijarro', 'ry-wc-city-select' ),
		'PRQU2' => __( 'Provincia Quillacollo', 'ry-wc-city-select' ),
		'PRRABU' => __( 'Provincia Rafael Bustillo', 'ry-wc-city-select' ),
		'PRSA' => __( 'Provincia Saavedra', 'ry-wc-city-select' ),
		'PRSA2' => __( 'Provincia Sabaya', 'ry-wc-city-select' ),
		'PRSA3' => __( 'Provincia Sajama', 'ry-wc-city-select' ),
		'PRSAPETO' => __( 'Provincia San Pedro de Totora', 'ry-wc-city-select' ),
		'PRSA4' => __( 'Provincia Santiesteban', 'ry-wc-city-select' ),
		'PRSA5' => __( 'Provincia Sara', 'ry-wc-city-select' ),
		'PRSA6' => __( 'Provincia Saucari', 'ry-wc-city-select' ),
		'PRSUCH' => __( 'Provincia Sud Chichas', 'ry-wc-city-select' ),
		'PRSUCI' => __( 'Provincia Sud Cinti', 'ry-wc-city-select' ),
		'PRSULI' => __( 'Provincia Sud Lipez', 'ry-wc-city-select' ),
		'PRSUYU' => __( 'Provincia Sud Yungas', 'ry-wc-city-select' ),
		'PRTA' => __( 'Provincia Tapacari', 'ry-wc-city-select' ),
		'PRTOBA' => __( 'Provincia Tomas Barron', 'ry-wc-city-select' ),
		'PRTOFR' => __( 'Provincia Tomas Frias', 'ry-wc-city-select' ),
		'PRTO' => __( 'Provincia Tomina', 'ry-wc-city-select' ),
		'PRVADI' => __( 'Provincia Vaca Diez', 'ry-wc-city-select' ),
		'PRVA' => __( 'Provincia Vallegrande', 'ry-wc-city-select' ),
		'PRVE' => __( 'Provincia Velasco', 'ry-wc-city-select' ),
		'PRWA' => __( 'Provincia Warnes', 'ry-wc-city-select' ),
		'PRYA' => __( 'Provincia Yacuma', 'ry-wc-city-select' ),
		'PRYA2' => __( 'Provincia Yamparaez', 'ry-wc-city-select' ),
		'PRZU' => __( 'Provincia Zudanez', 'ry-wc-city-select' ),
		'PUME' => __( 'Puerto de Mejillones', 'ry-wc-city-select' ),
		'SEPAPR' => __( 'Sebastian Pagador Province', 'ry-wc-city-select' ),
		'SUCAPR' => __( 'Sud Carangas Province', 'ry-wc-city-select' ),
		'TIPR' => __( 'Tiraque Province', 'ry-wc-city-select' ),
		'DECO' => __( 'Departamento de Cochabamba', 'ry-wc-city-select' ),
		'DEOR' => __( 'Departamento de Oruro', 'ry-wc-city-select' ),
		'DETA' => __( 'Departamento de Tarija', 'ry-wc-city-select' ),
		'DECH' => __( 'Departamento de Chuquisaca', 'ry-wc-city-select' ),
		'DEPA' => __( 'Departamento de La Paz', 'ry-wc-city-select' ),
		'DEPA2' => __( 'Departamento de Pando', 'ry-wc-city-select' ),
		'DEPO' => __( 'Departamento de Potosi', 'ry-wc-city-select' ),
		'DESACR' => __( 'Departamento de Santa Cruz', 'ry-wc-city-select' ),
		'BE' => __( 'El Beni', 'ry-wc-city-select' ),
	]
];