<?php
/**
 * Republic of France states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-19
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'FR' => [
		'AL' => __( 'Alpes-Maritimes', 'ry-wc-city-select' ),
		'AL2' => __( 'Alpes-de-Haute-Provence', 'ry-wc-city-select' ),
		'AR' => __( 'Ardennes', 'ry-wc-city-select' ),
		'BA' => __( 'Bas-Rhin', 'ry-wc-city-select' ),
		'CA' => __( 'Calvados', 'ry-wc-city-select' ),
		'CA2' => __( 'Cantal', 'ry-wc-city-select' ),
		'CH' => __( 'Charente', 'ry-wc-city-select' ),
		'CH2' => __( 'Charente-Maritime', 'ry-wc-city-select' ),
		'CH3' => __( 'Cher', 'ry-wc-city-select' ),
		'CR' => __( 'Creuse', 'ry-wc-city-select' ),
		'DEDE' => __( 'Departement dEure-et-Loir', 'ry-wc-city-select' ),
		'DEDI' => __( 'Departement dIlle-et-Vilaine', 'ry-wc-city-select' ),
		'DEDI2' => __( 'Departement dIndre-et-Loire', 'ry-wc-city-select' ),
		'DEMA' => __( 'Departement de Maine-et-Loire', 'ry-wc-city-select' ),
		'DESA' => __( 'Departement de Saone-et-Loire', 'ry-wc-city-select' ),
		'DELA' => __( 'Departement de lAin', 'ry-wc-city-select' ),
		'DELA2' => __( 'Departement de lAisne', 'ry-wc-city-select' ),
		'DELA3' => __( 'Departement de lAllier', 'ry-wc-city-select' ),
		'DELA4' => __( 'Departement de lArdeche', 'ry-wc-city-select' ),
		'DELA5' => __( 'Departement de lAriege', 'ry-wc-city-select' ),
		'DELA6' => __( 'Departement de lAube', 'ry-wc-city-select' ),
		'DELA7' => __( 'Departement de lAude', 'ry-wc-city-select' ),
		'DELA8' => __( 'Departement de lAveyron', 'ry-wc-city-select' ),
		'DELE' => __( 'Departement de lEssonne', 'ry-wc-city-select' ),
		'DELE2' => __( 'Departement de lEure', 'ry-wc-city-select' ),
		'DELH' => __( 'Departement de lHerault', 'ry-wc-city-select' ),
		'DELI' => __( 'Departement de lIndre', 'ry-wc-city-select' ),
		'DELI2' => __( 'Departement de lIsere', 'ry-wc-city-select' ),
		'DELO' => __( 'Departement de lOise', 'ry-wc-city-select' ),
		'DELO2' => __( 'Departement de lOrne', 'ry-wc-city-select' ),
		'DELY' => __( 'Departement de lYonne', 'ry-wc-city-select' ),
		'DECO' => __( 'Departement de la Correze', 'ry-wc-city-select' ),
		'DECO2' => __( 'Departement de la Corse-du-Sud', 'ry-wc-city-select' ),
		'DECO3' => __( 'Departement de la Cote-dOr', 'ry-wc-city-select' ),
		'DEDR' => __( 'Departement de la Drome', 'ry-wc-city-select' ),
		'DEHA' => __( 'Departement de la Haute-Corse', 'ry-wc-city-select' ),
		'DEHA2' => __( 'Departement de la Haute-Saone', 'ry-wc-city-select' ),
		'DELO3' => __( 'Departement de la Loire', 'ry-wc-city-select' ),
		'DELO4' => __( 'Departement de la Lozere', 'ry-wc-city-select' ),
		'DENI' => __( 'Departement de la Nievre', 'ry-wc-city-select' ),
		'DEVE' => __( 'Departement de la Vendee', 'ry-wc-city-select' ),
		'DEDEBO' => __( 'Departement des Bouches-du-Rhone', 'ry-wc-city-select' ),
		'DEDECO' => __( 'Departement des Cotes-dArmor', 'ry-wc-city-select' ),
		'DEDEDE' => __( 'Departement des Deux-Sevres', 'ry-wc-city-select' ),
		'DEDEHA' => __( 'Departement des Hautes-Pyrenees', 'ry-wc-city-select' ),
		'DEDEPY' => __( 'Departement des Pyrenees-Atlantiques', 'ry-wc-city-select' ),
		'DEDEPY2' => __( 'Departement des Pyrenees-Orientales', 'ry-wc-city-select' ),
		'DEFI' => __( 'Departement du Finistere', 'ry-wc-city-select' ),
		'DELO5' => __( 'Departement du Loir-et-Cher', 'ry-wc-city-select' ),
		'DELO6' => __( 'Departement du Lot-et-Garonne', 'ry-wc-city-select' ),
		'DEPU' => __( 'Departement du Puy-de-Dome', 'ry-wc-city-select' ),
		'DERH' => __( 'Departement du Rhone', 'ry-wc-city-select' ),
		'DETA' => __( 'Departement du Tarn-et-Garonne', 'ry-wc-city-select' ),
		'DEVA' => __( 'Departement du Val-dOise', 'ry-wc-city-select' ),
		'DEVA2' => __( 'Departement du Vaucluse', 'ry-wc-city-select' ),
		'DO' => __( 'Dordogne', 'ry-wc-city-select' ),
		'DO2' => __( 'Doubs', 'ry-wc-city-select' ),
		'GA' => __( 'Gard', 'ry-wc-city-select' ),
		'GE' => __( 'Gers', 'ry-wc-city-select' ),
		'GI' => __( 'Gironde', 'ry-wc-city-select' ),
		'HA' => __( 'Haut-Rhin', 'ry-wc-city-select' ),
		'HA2' => __( 'Haute-Garonne', 'ry-wc-city-select' ),
		'HA3' => __( 'Haute-Loire', 'ry-wc-city-select' ),
		'HA4' => __( 'Haute-Marne', 'ry-wc-city-select' ),
		'HA5' => __( 'Haute-Savoie', 'ry-wc-city-select' ),
		'HA6' => __( 'Haute-Vienne', 'ry-wc-city-select' ),
		'HA7' => __( 'Hautes-Alpes', 'ry-wc-city-select' ),
		'HA8' => __( 'Hauts-de-Seine', 'ry-wc-city-select' ),
		'JU' => __( 'Jura', 'ry-wc-city-select' ),
		'LA' => __( 'Landes', 'ry-wc-city-select' ),
		'LO' => __( 'Loire-Atlantique', 'ry-wc-city-select' ),
		'LO2' => __( 'Loiret', 'ry-wc-city-select' ),
		'LO3' => __( 'Lot', 'ry-wc-city-select' ),
		'MA' => __( 'Manche', 'ry-wc-city-select' ),
		'MA2' => __( 'Marne', 'ry-wc-city-select' ),
		'MA3' => __( 'Mayenne', 'ry-wc-city-select' ),
		'ME' => __( 'Meurthe-et-Moselle', 'ry-wc-city-select' ),
		'ME2' => __( 'Meuse', 'ry-wc-city-select' ),
		'MO' => __( 'Morbihan', 'ry-wc-city-select' ),
		'MO2' => __( 'Moselle', 'ry-wc-city-select' ),
		'NO' => __( 'Nord', 'ry-wc-city-select' ),
		'PA' => __( 'Paris', 'ry-wc-city-select' ),
		'PA2' => __( 'Pas-de-Calais', 'ry-wc-city-select' ),
		'SA' => __( 'Sarthe', 'ry-wc-city-select' ),
		'SA2' => __( 'Savoie', 'ry-wc-city-select' ),
		'SE' => __( 'Seine-Maritime', 'ry-wc-city-select' ),
		'SE2' => __( 'Seine-Saint-Denis', 'ry-wc-city-select' ),
		'SE3' => __( 'Seine-et-Marne', 'ry-wc-city-select' ),
		'SO' => __( 'Somme', 'ry-wc-city-select' ),
		'TA' => __( 'Tarn', 'ry-wc-city-select' ),
		'TEBE' => __( 'Territoire de Belfort', 'ry-wc-city-select' ),
		'VA' => __( 'Val-de-Marne', 'ry-wc-city-select' ),
		'VA2' => __( 'Var', 'ry-wc-city-select' ),
		'VI' => __( 'Vienne', 'ry-wc-city-select' ),
		'VO' => __( 'Vosges', 'ry-wc-city-select' ),
		'YV' => __( 'Yvelines', 'ry-wc-city-select' ),
		'AU' => __( 'Auvergne-Rhone-Alpes', 'ry-wc-city-select' ),
		'BO' => __( 'Bourgogne-Franche-Comte', 'ry-wc-city-select' ),
		'BR' => __( 'Bretagne', 'ry-wc-city-select' ),
		'CELO' => __( 'Centre-Val de Loire', 'ry-wc-city-select' ),
		'CO' => __( 'Corse', 'ry-wc-city-select' ),
		'GRES' => __( 'Grand Est', 'ry-wc-city-select' ),
		'HA9' => __( 'Hauts-de-France', 'ry-wc-city-select' ),
		'IL' => __( 'Ile-de-France', 'ry-wc-city-select' ),
		'NO2' => __( 'Normandie', 'ry-wc-city-select' ),
		'NO3' => __( 'Nouvelle-Aquitaine', 'ry-wc-city-select' ),
		'OC' => __( 'Occitanie', 'ry-wc-city-select' ),
		'PALO' => __( 'Pays de la Loire', 'ry-wc-city-select' ),
		'PRDA' => __( 'Provence-Alpes-Cote dAzur', 'ry-wc-city-select' ),
	]
];