<?php
/**
 * North Macedonia states
 *
 * @author   Sergio Caramanno
 * @version  2020-03-20
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'MK' => [
		'KR' => __( 'Kratovo', 'ry-wc-city-select' ),
		'KRPA' => __( 'Kriva Palanka', 'ry-wc-city-select' ),
		'KU' => __( 'Kumanovo', 'ry-wc-city-select' ),
		'MABR' => __( 'Makedonski Brod', 'ry-wc-city-select' ),
		'OH' => __( 'Ohrid', 'ry-wc-city-select' ),
		'OPKO' => __( 'Opstina Kocani', 'ry-wc-city-select' ),
		'OPKR' => __( 'Opstina Krusevo', 'ry-wc-city-select' ),
		'OPRA' => __( 'Opstina Radovis', 'ry-wc-city-select' ),
		'PE' => __( 'Petrovec', 'ry-wc-city-select' ),
		'ST' => __( 'Struga', 'ry-wc-city-select' ),
		'ST2' => __( 'Strumica', 'ry-wc-city-select' ),
		'TE' => __( 'Tetovo', 'ry-wc-city-select' ),
		'VE' => __( 'Veles', 'ry-wc-city-select' ),
		'VI' => __( 'Vinica', 'ry-wc-city-select' ),
		'AE' => __( 'Aerodrom', 'ry-wc-city-select' ),
		'BE' => __( 'Berovo', 'ry-wc-city-select' ),
		'BI' => __( 'Bitola', 'ry-wc-city-select' ),
		'BO' => __( 'Bogdanci', 'ry-wc-city-select' ),
		'BO2' => __( 'Bogovinje', 'ry-wc-city-select' ),
		'BO3' => __( 'Bosilovo', 'ry-wc-city-select' ),
		'BR' => __( 'Brvenica', 'ry-wc-city-select' ),
		'BU' => __( 'Butel', 'ry-wc-city-select' ),
		'CA' => __( 'Cair', 'ry-wc-city-select' ),
		'CE' => __( 'Cesinovo-Oblesevo', 'ry-wc-city-select' ),
		'DE' => __( 'Debar', 'ry-wc-city-select' ),
		'DE2' => __( 'Debarca', 'ry-wc-city-select' ),
		'DEHI' => __( 'Demir Hisar', 'ry-wc-city-select' ),
		'DEKA' => __( 'Demir Kapija', 'ry-wc-city-select' ),
		'DO' => __( 'Dolneni', 'ry-wc-city-select' ),
		'DR' => __( 'Drugovo', 'ry-wc-city-select' ),
		'GABA' => __( 'Gazi Baba', 'ry-wc-city-select' ),
		'GE' => __( 'Gevgelija', 'ry-wc-city-select' ),
		'GO' => __( 'Gostivar', 'ry-wc-city-select' ),
		'GRSK' => __( 'Grad Skopje', 'ry-wc-city-select' ),
		'GR' => __( 'Gradsko', 'ry-wc-city-select' ),
		'IL' => __( 'Ilinden', 'ry-wc-city-select' ),
		'JE' => __( 'Jegunovce', 'ry-wc-city-select' ),
		'KA' => __( 'Karbinci', 'ry-wc-city-select' ),
		'KA2' => __( 'Kavadarci', 'ry-wc-city-select' ),
		'KIVO' => __( 'Kisela Voda', 'ry-wc-city-select' ),
		'LO' => __( 'Lozovo', 'ry-wc-city-select' ),
		'MAKA' => __( 'Makedonska Kamenica', 'ry-wc-city-select' ),
		'MO' => __( 'Mogila', 'ry-wc-city-select' ),
		'NE' => __( 'Negotino', 'ry-wc-city-select' ),
		'NO' => __( 'Novaci', 'ry-wc-city-select' ),
		'NOSE' => __( 'Novo Selo', 'ry-wc-city-select' ),
		'OPAR' => __( 'Opstina Aracinovo', 'ry-wc-city-select' ),
		'OPCA' => __( 'Opstina Caska', 'ry-wc-city-select' ),
		'OPCE' => __( 'Opstina Centar', 'ry-wc-city-select' ),
		'OPCEZU' => __( 'Opstina Centar Zupa', 'ry-wc-city-select' ),
		'OPCU' => __( 'Opstina Cucer-Sandevo', 'ry-wc-city-select' ),
		'OPDE' => __( 'Opstina Delcevo', 'ry-wc-city-select' ),
		'OPDO' => __( 'Opstina Dojran', 'ry-wc-city-select' ),
		'OPGJPE' => __( 'Opstina Gjorce Petrov', 'ry-wc-city-select' ),
		'OPKA' => __( 'Opstina Karpos', 'ry-wc-city-select' ),
		'OPKI' => __( 'Opstina Kicevo', 'ry-wc-city-select' ),
		'OPKO2' => __( 'Opstina Konce', 'ry-wc-city-select' ),
		'OPKR2' => __( 'Opstina Krivogastani', 'ry-wc-city-select' ),
		'OPLI' => __( 'Opstina Lipkovo', 'ry-wc-city-select' ),
		'OPMARO' => __( 'Opstina Mavrovo i Rostusa', 'ry-wc-city-select' ),
		'OPPE' => __( 'Opstina Pehcevo', 'ry-wc-city-select' ),
		'OPPR' => __( 'Opstina Probistip', 'ry-wc-city-select' ),
		'OPRA2' => __( 'Opstina Rankovce', 'ry-wc-city-select' ),
		'OPSO' => __( 'Opstina Sopiste', 'ry-wc-city-select' ),
		'OPSTNA' => __( 'Opstina Staro Nagoricane', 'ry-wc-city-select' ),
		'OPST' => __( 'Opstina Stip', 'ry-wc-city-select' ),
		'OPST2' => __( 'Opstina Studenicani', 'ry-wc-city-select' ),
		'OPVE' => __( 'Opstina Vevcani', 'ry-wc-city-select' ),
		'OPVR' => __( 'Opstina Vranestica', 'ry-wc-city-select' ),
		'OPVR2' => __( 'Opstina Vrapciste', 'ry-wc-city-select' ),
		'OPZE' => __( 'Opstina Zelino', 'ry-wc-city-select' ),
		'OS' => __( 'Oslomej', 'ry-wc-city-select' ),
		'PL' => __( 'Plasnica', 'ry-wc-city-select' ),
		'PR' => __( 'Prilep', 'ry-wc-city-select' ),
		'RE' => __( 'Resen', 'ry-wc-city-select' ),
		'RO' => __( 'Rosoman', 'ry-wc-city-select' ),
		'SA' => __( 'Saraj', 'ry-wc-city-select' ),
		'SUOR' => __( 'Suto Orizari', 'ry-wc-city-select' ),
		'SVNI' => __( 'Sveti Nikole', 'ry-wc-city-select' ),
		'TE2' => __( 'Tearce', 'ry-wc-city-select' ),
		'VA' => __( 'Valandovo', 'ry-wc-city-select' ),
		'VA2' => __( 'Vasilevo', 'ry-wc-city-select' ),
		'ZA' => __( 'Zajas', 'ry-wc-city-select' ),
		'ZE' => __( 'Zelenikovo', 'ry-wc-city-select' ),
		'ZR' => __( 'Zrnovci', 'ry-wc-city-select' ),
	]
	]
];