<?php
/**
 * Republic of Ghana places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-19
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'GH' => [
	'ASRE' => [
		_x('Adansi North', 'ASRE', 'ry-wc-city-select'),
		_x('Adansi South', 'ASRE', 'ry-wc-city-select'),
		_x('Afigya-Kwabre District', 'ASRE', 'ry-wc-city-select'),
		_x('Ahafo Ano North', 'ASRE', 'ry-wc-city-select'),
		_x('Ahafo Ano South', 'ASRE', 'ry-wc-city-select'),
		_x('Amansie Central', 'ASRE', 'ry-wc-city-select'),
		_x('Amansie East', 'ASRE', 'ry-wc-city-select'),
		_x('Amansie West', 'ASRE', 'ry-wc-city-select'),
		_x('Asante Akim North', 'ASRE', 'ry-wc-city-select'),
		_x('Asante Akim South District', 'ASRE', 'ry-wc-city-select'),
		_x('Atwima Kwanwoma', 'ASRE', 'ry-wc-city-select'),
		_x('Atwima Mponua', 'ASRE', 'ry-wc-city-select'),
		_x('Atwima Nwabiagya', 'ASRE', 'ry-wc-city-select'),
		_x('Bekwai', 'ASRE', 'ry-wc-city-select'),
		_x('Bekwai Municipal District', 'ASRE', 'ry-wc-city-select'),
		_x('Bosome Freho', 'ASRE', 'ry-wc-city-select'),
		_x('Bosomtwe', 'ASRE', 'ry-wc-city-select'),
		_x('Ejisu Juaben', 'ASRE', 'ry-wc-city-select'),
		_x('Ejura Sekyedumase', 'ASRE', 'ry-wc-city-select'),
		_x('Kumasi', 'ASRE', 'ry-wc-city-select'),
		_x('Kumasi Metropolitan District', 'ASRE', 'ry-wc-city-select'),
		_x('Kwabre District', 'ASRE', 'ry-wc-city-select'),
		_x('Mampong', 'ASRE', 'ry-wc-city-select'),
		_x('Obuasi', 'ASRE', 'ry-wc-city-select'),
		_x('Obuasi Municipal District', 'ASRE', 'ry-wc-city-select'),
		_x('Offinso', 'ASRE', 'ry-wc-city-select'),
		_x('Offinso Municipal District', 'ASRE', 'ry-wc-city-select'),
		_x('Offinso North', 'ASRE', 'ry-wc-city-select'),
		_x('Sekyere Afram Plains', 'ASRE', 'ry-wc-city-select'),
		_x('Sekyere Central', 'ASRE', 'ry-wc-city-select'),
		_x('Sekyere East', 'ASRE', 'ry-wc-city-select'),
		_x('Sekyere South', 'ASRE', 'ry-wc-city-select'),
	],
	'BRRE' => [
		_x('Asunafo North', 'BRRE', 'ry-wc-city-select'),
		_x('Asunafo South', 'BRRE', 'ry-wc-city-select'),
		_x('Asutifi', 'BRRE', 'ry-wc-city-select'),
		_x('Atebubu-Amantin District', 'BRRE', 'ry-wc-city-select'),
		_x('Berekum', 'BRRE', 'ry-wc-city-select'),
		_x('Dormaa', 'BRRE', 'ry-wc-city-select'),
		_x('Dormaa East new', 'BRRE', 'ry-wc-city-select'),
		_x('Jaman North', 'BRRE', 'ry-wc-city-select'),
		_x('Jaman South', 'BRRE', 'ry-wc-city-select'),
		_x('Kintampo North Municipal District', 'BRRE', 'ry-wc-city-select'),
		_x('Kintampo South District', 'BRRE', 'ry-wc-city-select'),
		_x('Nkoranza North District', 'BRRE', 'ry-wc-city-select'),
		_x('Nkoranza South', 'BRRE', 'ry-wc-city-select'),
		_x('Pru', 'BRRE', 'ry-wc-city-select'),
		_x('Sene', 'BRRE', 'ry-wc-city-select'),
		_x('Sunyani', 'BRRE', 'ry-wc-city-select'),
		_x('Sunyani West', 'BRRE', 'ry-wc-city-select'),
		_x('Tain', 'BRRE', 'ry-wc-city-select'),
		_x('Tano North', 'BRRE', 'ry-wc-city-select'),
		_x('Tano South', 'BRRE', 'ry-wc-city-select'),
		_x('Techiman Municipal District', 'BRRE', 'ry-wc-city-select'),
		_x('Wenchi', 'BRRE', 'ry-wc-city-select'),
	],
	'CERE' => [
		_x('Abura/Asebu/Kwamankese', 'CERE', 'ry-wc-city-select'),
		_x('Agona East', 'CERE', 'ry-wc-city-select'),
		_x('Agona West', 'CERE', 'ry-wc-city-select'),
		_x('Ajumako/Enyan/Essiam', 'CERE', 'ry-wc-city-select'),
		_x('Ajumako/Enyan/Essiam District', 'CERE', 'ry-wc-city-select'),
		_x('Asikuma/Odoben/Brakwa', 'CERE', 'ry-wc-city-select'),
		_x('Assin North', 'CERE', 'ry-wc-city-select'),
		_x('Assin South', 'CERE', 'ry-wc-city-select'),
		_x('Awutu Senya', 'CERE', 'ry-wc-city-select'),
		_x('Cape Coast', 'CERE', 'ry-wc-city-select'),
		_x('Effutu', 'CERE', 'ry-wc-city-select'),
		_x('Gomoa East', 'CERE', 'ry-wc-city-select'),
		_x('Gomoa West', 'CERE', 'ry-wc-city-select'),
		_x('Komenda/Edina/Eguafo/Abirem', 'CERE', 'ry-wc-city-select'),
		_x('Mfatseman', 'CERE', 'ry-wc-city-select'),
		_x('Twifo Hemang Lower Denkyira', 'CERE', 'ry-wc-city-select'),
		_x('Upper Denkyira', 'CERE', 'ry-wc-city-select'),
		_x('Upper Denkyira East', 'CERE', 'ry-wc-city-select'),
		_x('Upper Denkyira West', 'CERE', 'ry-wc-city-select'),
	],
	'EARE' => [
		_x('Akuapim North', 'EARE', 'ry-wc-city-select'),
		_x('Akuapim North District', 'EARE', 'ry-wc-city-select'),
		_x('Akuapim South', 'EARE', 'ry-wc-city-select'),
		_x('Akyemansa', 'EARE', 'ry-wc-city-select'),
		_x('Asuogyaman', 'EARE', 'ry-wc-city-select'),
		_x('Atiwa', 'EARE', 'ry-wc-city-select'),
		_x('Birim Central', 'EARE', 'ry-wc-city-select'),
		_x('Birim North', 'EARE', 'ry-wc-city-select'),
		_x('Birim South', 'EARE', 'ry-wc-city-select'),
		_x('Dangme East District', 'EARE', 'ry-wc-city-select'),
		_x('Dangme West District', 'EARE', 'ry-wc-city-select'),
		_x('East Akim', 'EARE', 'ry-wc-city-select'),
		_x('Fanteakwa', 'EARE', 'ry-wc-city-select'),
		_x('Kwaebibirem', 'EARE', 'ry-wc-city-select'),
		_x('Kwahu East', 'EARE', 'ry-wc-city-select'),
		_x('Kwahu North', 'EARE', 'ry-wc-city-select'),
		_x('Kwahu South', 'EARE', 'ry-wc-city-select'),
		_x('Kwahu West', 'EARE', 'ry-wc-city-select'),
		_x('Lower Manya Krobo', 'EARE', 'ry-wc-city-select'),
		_x('New Juaben', 'EARE', 'ry-wc-city-select'),
		_x('Somanya District', 'EARE', 'ry-wc-city-select'),
		_x('Suhum/Kraboa/Coaltar', 'EARE', 'ry-wc-city-select'),
		_x('Upper Manya Krobo', 'EARE', 'ry-wc-city-select'),
		_x('West Akim', 'EARE', 'ry-wc-city-select'),
		_x('Yilo Krobo', 'EARE', 'ry-wc-city-select'),
	],
	'GRACRE' => [
		_x('Accra', 'GRACRE', 'ry-wc-city-select'),
		_x('Accra Metropolis District', 'GRACRE', 'ry-wc-city-select'),
		_x('Adenta', 'GRACRE', 'ry-wc-city-select'),
		_x('Ashaiman', 'GRACRE', 'ry-wc-city-select'),
		_x('Ga Central Municipal Assembly', 'GRACRE', 'ry-wc-city-select'),
		_x('Ga East', 'GRACRE', 'ry-wc-city-select'),
		_x('Ga South Municipal Assembly', 'GRACRE', 'ry-wc-city-select'),
		_x('Ga West', 'GRACRE', 'ry-wc-city-select'),
		_x('Ledzekuku-Krowor', 'GRACRE', 'ry-wc-city-select'),
		_x('Tema Metropolitan District', 'GRACRE', 'ry-wc-city-select'),
		_x('Weija', 'GRACRE', 'ry-wc-city-select'),
	],
	'NORE' => [
		_x('Bole', 'NORE', 'ry-wc-city-select'),
		_x('Bole District', 'NORE', 'ry-wc-city-select'),
		_x('Bunkpurugu-Yunyoo', 'NORE', 'ry-wc-city-select'),
		_x('Central Gonja', 'NORE', 'ry-wc-city-select'),
		_x('Chereponi', 'NORE', 'ry-wc-city-select'),
		_x('Dagomba', 'NORE', 'ry-wc-city-select'),
		_x('East Gonja', 'NORE', 'ry-wc-city-select'),
		_x('East Mamprusi', 'NORE', 'ry-wc-city-select'),
		_x('Gushegu District', 'NORE', 'ry-wc-city-select'),
		_x('Gushiegu', 'NORE', 'ry-wc-city-select'),
		_x('Karaga', 'NORE', 'ry-wc-city-select'),
		_x('Kpandai', 'NORE', 'ry-wc-city-select'),
		_x('Mamprugo Moaduri District', 'NORE', 'ry-wc-city-select'),
		_x('Nanumba North', 'NORE', 'ry-wc-city-select'),
		_x('Nanumba South', 'NORE', 'ry-wc-city-select'),
		_x('Saboba', 'NORE', 'ry-wc-city-select'),
		_x('Saboba Chereponi', 'NORE', 'ry-wc-city-select'),
		_x('Savelugu/Nanton', 'NORE', 'ry-wc-city-select'),
		_x('Sawla-Tuna-Kalba', 'NORE', 'ry-wc-city-select'),
		_x('Tamale', 'NORE', 'ry-wc-city-select'),
		_x('Tolon/Kumbungu', 'NORE', 'ry-wc-city-select'),
		_x('West Gonja', 'NORE', 'ry-wc-city-select'),
		_x('West Mamprusi', 'NORE', 'ry-wc-city-select'),
		_x('Yendi', 'NORE', 'ry-wc-city-select'),
		_x('Zabzugu/Tatale', 'NORE', 'ry-wc-city-select'),
	],
	'UPEARE' => [
		_x('Bawku', 'UPEARE', 'ry-wc-city-select'),
		_x('Bawku Municipal District', 'UPEARE', 'ry-wc-city-select'),
		_x('Bawku West', 'UPEARE', 'ry-wc-city-select'),
		_x('Bawku West District', 'UPEARE', 'ry-wc-city-select'),
		_x('Binduri District', 'UPEARE', 'ry-wc-city-select'),
		_x('Bolgatanga', 'UPEARE', 'ry-wc-city-select'),
		_x('Bongo', 'UPEARE', 'ry-wc-city-select'),
		_x('Builsa', 'UPEARE', 'ry-wc-city-select'),
		_x('Garu-Tempane', 'UPEARE', 'ry-wc-city-select'),
		_x('Kassena Nankana', 'UPEARE', 'ry-wc-city-select'),
		_x('Kassena Nankana West', 'UPEARE', 'ry-wc-city-select'),
		_x('Talensi-Nabdam', 'UPEARE', 'ry-wc-city-select'),
	],
	'UPWERE' => [
		_x('Daffiama Bussie Issa District', 'UPWERE', 'ry-wc-city-select'),
		_x('Jirapa', 'UPWERE', 'ry-wc-city-select'),
		_x('Jirapa Lambussie', 'UPWERE', 'ry-wc-city-select'),
		_x('Lambussie Karni', 'UPWERE', 'ry-wc-city-select'),
		_x('Lawra', 'UPWERE', 'ry-wc-city-select'),
		_x('Nadowli', 'UPWERE', 'ry-wc-city-select'),
		_x('Sissala East', 'UPWERE', 'ry-wc-city-select'),
		_x('Sissala West', 'UPWERE', 'ry-wc-city-select'),
		_x('Wa', 'UPWERE', 'ry-wc-city-select'),
		_x('Wa East', 'UPWERE', 'ry-wc-city-select'),
		_x('Wa West', 'UPWERE', 'ry-wc-city-select'),
	],
	'VORE' => [
		_x('Adaklu-Anyigbe', 'VORE', 'ry-wc-city-select'),
		_x('Akatsi District', 'VORE', 'ry-wc-city-select'),
		_x('Biakoye', 'VORE', 'ry-wc-city-select'),
		_x('Ho', 'VORE', 'ry-wc-city-select'),
		_x('Hohoe', 'VORE', 'ry-wc-city-select'),
		_x('Jasikan', 'VORE', 'ry-wc-city-select'),
		_x('Kadjebi', 'VORE', 'ry-wc-city-select'),
		_x('Keta', 'VORE', 'ry-wc-city-select'),
		_x('Ketu North District', 'VORE', 'ry-wc-city-select'),
		_x('Ketu South District', 'VORE', 'ry-wc-city-select'),
		_x('Kpando', 'VORE', 'ry-wc-city-select'),
		_x('Krachi East', 'VORE', 'ry-wc-city-select'),
		_x('Krachi West', 'VORE', 'ry-wc-city-select'),
		_x('Nkwanta North', 'VORE', 'ry-wc-city-select'),
		_x('Nkwanta South', 'VORE', 'ry-wc-city-select'),
		_x('North Tongu', 'VORE', 'ry-wc-city-select'),
		_x('South Dayi', 'VORE', 'ry-wc-city-select'),
		_x('South Tongu District', 'VORE', 'ry-wc-city-select'),
	],
	'WERE' => [
		_x('Ahanta West', 'WERE', 'ry-wc-city-select'),
		_x('Aowin/Suaman', 'WERE', 'ry-wc-city-select'),
		_x('Bia', 'WERE', 'ry-wc-city-select'),
		_x('Bibiani/Ahwiaso/Bekwai', 'WERE', 'ry-wc-city-select'),
		_x('Ellembelle', 'WERE', 'ry-wc-city-select'),
		_x('Jomoro', 'WERE', 'ry-wc-city-select'),
		_x('Juaboso', 'WERE', 'ry-wc-city-select'),
		_x('Mpohor/Wassa East', 'WERE', 'ry-wc-city-select'),
		_x('Nzema East', 'WERE', 'ry-wc-city-select'),
		_x('Prestea-Huni Valley', 'WERE', 'ry-wc-city-select'),
		_x('Secondi Takoradi', 'WERE', 'ry-wc-city-select'),
		_x('Sefwi Akontobra', 'WERE', 'ry-wc-city-select'),
		_x('Sefwi-Wiawso', 'WERE', 'ry-wc-city-select'),
		_x('Shama Ahanta East Metropolitan District', 'WERE', 'ry-wc-city-select'),
		_x('Shama new', 'WERE', 'ry-wc-city-select'),
		_x('Tarkwa Nsuaem', 'WERE', 'ry-wc-city-select'),
		_x('Wassa Amenfi East', 'WERE', 'ry-wc-city-select'),
		_x('Wassa Amenfi West', 'WERE', 'ry-wc-city-select'),
		_x('Wassa West', 'WERE', 'ry-wc-city-select'),
	],
	]
];