<?php
/**
 * Kingdom of Norway places
 *
 * @author   Sergio Caramanno
 * @version  2020-03-19
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Data from: http://geonames.org/
 */

return [
	'NO' => [
	'OS' => [
		_x('Alna District', 'OS', 'ry-wc-city-select'),
		_x('Bjerke District', 'OS', 'ry-wc-city-select'),
		_x('Frogner District', 'OS', 'ry-wc-city-select'),
		_x('Gamle Oslo District', 'OS', 'ry-wc-city-select'),
		_x('Grorud District', 'OS', 'ry-wc-city-select'),
		_x('Gruenerlokka District', 'OS', 'ry-wc-city-select'),
		_x('Marka', 'OS', 'ry-wc-city-select'),
		_x('Nordre Aker District', 'OS', 'ry-wc-city-select'),
		_x('Nordstrand District', 'OS', 'ry-wc-city-select'),
		_x('Sagene District', 'OS', 'ry-wc-city-select'),
		_x('Sentrum', 'OS', 'ry-wc-city-select'),
		_x('Sondre Nordstrand District', 'OS', 'ry-wc-city-select'),
		_x('St. Hanshaugen District', 'OS', 'ry-wc-city-select'),
		_x('Ullern District', 'OS', 'ry-wc-city-select'),
		_x('Vestre Aker District', 'OS', 'ry-wc-city-select'),
	],
	'AKFY' => [
		_x('As', 'AKFY', 'ry-wc-city-select'),
		_x('Asker', 'AKFY', 'ry-wc-city-select'),
		_x('Aurskog-Holand', 'AKFY', 'ry-wc-city-select'),
		_x('Baerum', 'AKFY', 'ry-wc-city-select'),
		_x('Eidsvoll', 'AKFY', 'ry-wc-city-select'),
		_x('Enebakk', 'AKFY', 'ry-wc-city-select'),
		_x('Fet', 'AKFY', 'ry-wc-city-select'),
		_x('Frogn', 'AKFY', 'ry-wc-city-select'),
		_x('Gjerdrum', 'AKFY', 'ry-wc-city-select'),
		_x('Hurdal', 'AKFY', 'ry-wc-city-select'),
		_x('Lorenskog', 'AKFY', 'ry-wc-city-select'),
		_x('Nannestad', 'AKFY', 'ry-wc-city-select'),
		_x('Nes', 'AKFY', 'ry-wc-city-select'),
		_x('Nesodden', 'AKFY', 'ry-wc-city-select'),
		_x('Nittedal', 'AKFY', 'ry-wc-city-select'),
		_x('Oppegard', 'AKFY', 'ry-wc-city-select'),
		_x('Raelingen', 'AKFY', 'ry-wc-city-select'),
		_x('Skedsmo', 'AKFY', 'ry-wc-city-select'),
		_x('Ski', 'AKFY', 'ry-wc-city-select'),
		_x('Sorum', 'AKFY', 'ry-wc-city-select'),
		_x('Ullensaker', 'AKFY', 'ry-wc-city-select'),
		_x('Vestby', 'AKFY', 'ry-wc-city-select'),
	],
	'AUFY' => [
		_x('Amli', 'AUFY', 'ry-wc-city-select'),
		_x('Arendal', 'AUFY', 'ry-wc-city-select'),
		_x('Birkenes', 'AUFY', 'ry-wc-city-select'),
		_x('Bygland', 'AUFY', 'ry-wc-city-select'),
		_x('Bykle', 'AUFY', 'ry-wc-city-select'),
		_x('Evje og Hornnes', 'AUFY', 'ry-wc-city-select'),
		_x('Froland', 'AUFY', 'ry-wc-city-select'),
		_x('Gjerstad', 'AUFY', 'ry-wc-city-select'),
		_x('Grimstad', 'AUFY', 'ry-wc-city-select'),
		_x('Iveland', 'AUFY', 'ry-wc-city-select'),
		_x('Lillesand', 'AUFY', 'ry-wc-city-select'),
		_x('Risor', 'AUFY', 'ry-wc-city-select'),
		_x('Tvedestrand', 'AUFY', 'ry-wc-city-select'),
		_x('Valle', 'AUFY', 'ry-wc-city-select'),
		_x('Vegarshei', 'AUFY', 'ry-wc-city-select'),
	],
	'BUFY' => [
		_x('Al', 'BUFY', 'ry-wc-city-select'),
		_x('Drammen', 'BUFY', 'ry-wc-city-select'),
		_x('Fla', 'BUFY', 'ry-wc-city-select'),
		_x('Flesberg', 'BUFY', 'ry-wc-city-select'),
		_x('Gol', 'BUFY', 'ry-wc-city-select'),
		_x('Hemsedal', 'BUFY', 'ry-wc-city-select'),
		_x('Hol', 'BUFY', 'ry-wc-city-select'),
		_x('Hole', 'BUFY', 'ry-wc-city-select'),
		_x('Hurum', 'BUFY', 'ry-wc-city-select'),
		_x('Kongsberg', 'BUFY', 'ry-wc-city-select'),
		_x('Krodsherad', 'BUFY', 'ry-wc-city-select'),
		_x('Lier', 'BUFY', 'ry-wc-city-select'),
		_x('Modum', 'BUFY', 'ry-wc-city-select'),
		_x('Nedre Eiker', 'BUFY', 'ry-wc-city-select'),
		_x('Nes', 'BUFY', 'ry-wc-city-select'),
		_x('Nore og Uvdal', 'BUFY', 'ry-wc-city-select'),
		_x('Ovre Eiker', 'BUFY', 'ry-wc-city-select'),
		_x('Ringerike', 'BUFY', 'ry-wc-city-select'),
		_x('Rollag', 'BUFY', 'ry-wc-city-select'),
		_x('Royken', 'BUFY', 'ry-wc-city-select'),
		_x('Sigdal', 'BUFY', 'ry-wc-city-select'),
	],
	'FIFY' => [
		_x('Alta', 'FIFY', 'ry-wc-city-select'),
		_x('Batsfjord', 'FIFY', 'ry-wc-city-select'),
		_x('Berlevag', 'FIFY', 'ry-wc-city-select'),
		_x('Gamvik', 'FIFY', 'ry-wc-city-select'),
		_x('Hammerfest', 'FIFY', 'ry-wc-city-select'),
		_x('Hasvik', 'FIFY', 'ry-wc-city-select'),
		_x('Karasjok', 'FIFY', 'ry-wc-city-select'),
		_x('Kautokeino', 'FIFY', 'ry-wc-city-select'),
		_x('Kvalsund', 'FIFY', 'ry-wc-city-select'),
		_x('Lebesby', 'FIFY', 'ry-wc-city-select'),
		_x('Loppa', 'FIFY', 'ry-wc-city-select'),
		_x('Masoy', 'FIFY', 'ry-wc-city-select'),
		_x('Nesseby', 'FIFY', 'ry-wc-city-select'),
		_x('Nordkapp', 'FIFY', 'ry-wc-city-select'),
		_x('Porsanger', 'FIFY', 'ry-wc-city-select'),
		_x('Sor-Varanger', 'FIFY', 'ry-wc-city-select'),
		_x('Tana', 'FIFY', 'ry-wc-city-select'),
		_x('Vadso', 'FIFY', 'ry-wc-city-select'),
		_x('Vardo', 'FIFY', 'ry-wc-city-select'),
	],
	'HEFY' => [
		_x('Alvdal', 'HEFY', 'ry-wc-city-select'),
		_x('Amot', 'HEFY', 'ry-wc-city-select'),
		_x('Asnes', 'HEFY', 'ry-wc-city-select'),
		_x('Eidskog', 'HEFY', 'ry-wc-city-select'),
		_x('Elverum', 'HEFY', 'ry-wc-city-select'),
		_x('Engerdal', 'HEFY', 'ry-wc-city-select'),
		_x('Folldal', 'HEFY', 'ry-wc-city-select'),
		_x('Grue', 'HEFY', 'ry-wc-city-select'),
		_x('Hamar', 'HEFY', 'ry-wc-city-select'),
		_x('Kongsvinger', 'HEFY', 'ry-wc-city-select'),
		_x('Loten', 'HEFY', 'ry-wc-city-select'),
		_x('Nord-Odal', 'HEFY', 'ry-wc-city-select'),
		_x('Os', 'HEFY', 'ry-wc-city-select'),
		_x('Rendalen', 'HEFY', 'ry-wc-city-select'),
		_x('Ringsaker', 'HEFY', 'ry-wc-city-select'),
		_x('Sor-Odal', 'HEFY', 'ry-wc-city-select'),
		_x('Stange', 'HEFY', 'ry-wc-city-select'),
		_x('Stor-Elvdal', 'HEFY', 'ry-wc-city-select'),
		_x('Tolga', 'HEFY', 'ry-wc-city-select'),
		_x('Trysil', 'HEFY', 'ry-wc-city-select'),
		_x('Tynset', 'HEFY', 'ry-wc-city-select'),
		_x('Valer', 'HEFY', 'ry-wc-city-select'),
	],
	'HOFY' => [
		_x('Askoy', 'HOFY', 'ry-wc-city-select'),
		_x('Austevoll', 'HOFY', 'ry-wc-city-select'),
		_x('Austrheim', 'HOFY', 'ry-wc-city-select'),
		_x('Bergen', 'HOFY', 'ry-wc-city-select'),
		_x('Bomlo', 'HOFY', 'ry-wc-city-select'),
		_x('Eidfjord', 'HOFY', 'ry-wc-city-select'),
		_x('Etne', 'HOFY', 'ry-wc-city-select'),
		_x('Fedje', 'HOFY', 'ry-wc-city-select'),
		_x('Fitjar', 'HOFY', 'ry-wc-city-select'),
		_x('Fjell', 'HOFY', 'ry-wc-city-select'),
		_x('Fusa', 'HOFY', 'ry-wc-city-select'),
		_x('Granvin', 'HOFY', 'ry-wc-city-select'),
		_x('Jondal', 'HOFY', 'ry-wc-city-select'),
		_x('Kvam', 'HOFY', 'ry-wc-city-select'),
		_x('Kvinnherad', 'HOFY', 'ry-wc-city-select'),
		_x('Lindas', 'HOFY', 'ry-wc-city-select'),
		_x('Masfjorden', 'HOFY', 'ry-wc-city-select'),
		_x('Meland', 'HOFY', 'ry-wc-city-select'),
		_x('Modalen', 'HOFY', 'ry-wc-city-select'),
		_x('Odda', 'HOFY', 'ry-wc-city-select'),
		_x('Os', 'HOFY', 'ry-wc-city-select'),
		_x('Osteroy', 'HOFY', 'ry-wc-city-select'),
		_x('Oygarden', 'HOFY', 'ry-wc-city-select'),
		_x('Radoy', 'HOFY', 'ry-wc-city-select'),
		_x('Samnanger', 'HOFY', 'ry-wc-city-select'),
		_x('Stord', 'HOFY', 'ry-wc-city-select'),
		_x('Sund', 'HOFY', 'ry-wc-city-select'),
		_x('Sveio', 'HOFY', 'ry-wc-city-select'),
		_x('Tysnes', 'HOFY', 'ry-wc-city-select'),
		_x('Ullensvang', 'HOFY', 'ry-wc-city-select'),
		_x('Ulvik', 'HOFY', 'ry-wc-city-select'),
		_x('Vaksdal', 'HOFY', 'ry-wc-city-select'),
		_x('Voss', 'HOFY', 'ry-wc-city-select'),
	],
	'MOROFY' => [
		_x('Alesund', 'MOROFY', 'ry-wc-city-select'),
		_x('Aukra', 'MOROFY', 'ry-wc-city-select'),
		_x('Aure', 'MOROFY', 'ry-wc-city-select'),
		_x('Averoy', 'MOROFY', 'ry-wc-city-select'),
		_x('Eide', 'MOROFY', 'ry-wc-city-select'),
		_x('Fraena', 'MOROFY', 'ry-wc-city-select'),
		_x('Giske', 'MOROFY', 'ry-wc-city-select'),
		_x('Gjemnes', 'MOROFY', 'ry-wc-city-select'),
		_x('Halsa', 'MOROFY', 'ry-wc-city-select'),
		_x('Haram', 'MOROFY', 'ry-wc-city-select'),
		_x('Hareid', 'MOROFY', 'ry-wc-city-select'),
		_x('Heroy', 'MOROFY', 'ry-wc-city-select'),
		_x('Kristiansund', 'MOROFY', 'ry-wc-city-select'),
		_x('Midsund', 'MOROFY', 'ry-wc-city-select'),
		_x('Molde', 'MOROFY', 'ry-wc-city-select'),
		_x('Nesset', 'MOROFY', 'ry-wc-city-select'),
		_x('Norddal', 'MOROFY', 'ry-wc-city-select'),
		_x('Orskog', 'MOROFY', 'ry-wc-city-select'),
		_x('Orsta', 'MOROFY', 'ry-wc-city-select'),
		_x('Rauma', 'MOROFY', 'ry-wc-city-select'),
		_x('Rindal', 'MOROFY', 'ry-wc-city-select'),
		_x('Sande', 'MOROFY', 'ry-wc-city-select'),
		_x('Sandoy', 'MOROFY', 'ry-wc-city-select'),
		_x('Skodje', 'MOROFY', 'ry-wc-city-select'),
		_x('Smola', 'MOROFY', 'ry-wc-city-select'),
		_x('Stordal', 'MOROFY', 'ry-wc-city-select'),
		_x('Stranda', 'MOROFY', 'ry-wc-city-select'),
		_x('Sula', 'MOROFY', 'ry-wc-city-select'),
		_x('Sunndal', 'MOROFY', 'ry-wc-city-select'),
		_x('Surnadal', 'MOROFY', 'ry-wc-city-select'),
		_x('Sykkylven', 'MOROFY', 'ry-wc-city-select'),
		_x('Tingvoll', 'MOROFY', 'ry-wc-city-select'),
		_x('Ulstein', 'MOROFY', 'ry-wc-city-select'),
		_x('Vanylven', 'MOROFY', 'ry-wc-city-select'),
		_x('Vestnes', 'MOROFY', 'ry-wc-city-select'),
		_x('Volda', 'MOROFY', 'ry-wc-city-select'),
	],
	'NOFY' => [
		_x('Alstahaug', 'NOFY', 'ry-wc-city-select'),
		_x('Andoy', 'NOFY', 'ry-wc-city-select'),
		_x('Ballangen', 'NOFY', 'ry-wc-city-select'),
		_x('Beiarn', 'NOFY', 'ry-wc-city-select'),
		_x('Bindal', 'NOFY', 'ry-wc-city-select'),
		_x('Bo', 'NOFY', 'ry-wc-city-select'),
		_x('Bodo', 'NOFY', 'ry-wc-city-select'),
		_x('Bronnoy', 'NOFY', 'ry-wc-city-select'),
		_x('Donna', 'NOFY', 'ry-wc-city-select'),
		_x('Evenes', 'NOFY', 'ry-wc-city-select'),
		_x('Fauske', 'NOFY', 'ry-wc-city-select'),
		_x('Flakstad', 'NOFY', 'ry-wc-city-select'),
		_x('Gildeskal', 'NOFY', 'ry-wc-city-select'),
		_x('Grane', 'NOFY', 'ry-wc-city-select'),
		_x('Hadsel', 'NOFY', 'ry-wc-city-select'),
		_x('Hamaroy', 'NOFY', 'ry-wc-city-select'),
		_x('Hattfjelldal', 'NOFY', 'ry-wc-city-select'),
		_x('Hemnes', 'NOFY', 'ry-wc-city-select'),
		_x('Heroy', 'NOFY', 'ry-wc-city-select'),
		_x('Leirfjord', 'NOFY', 'ry-wc-city-select'),
		_x('Lodingen', 'NOFY', 'ry-wc-city-select'),
		_x('Luroy', 'NOFY', 'ry-wc-city-select'),
		_x('Meloy', 'NOFY', 'ry-wc-city-select'),
		_x('Moskenes', 'NOFY', 'ry-wc-city-select'),
		_x('Narvik', 'NOFY', 'ry-wc-city-select'),
		_x('Nesna', 'NOFY', 'ry-wc-city-select'),
		_x('Oksnes', 'NOFY', 'ry-wc-city-select'),
		_x('Rana', 'NOFY', 'ry-wc-city-select'),
		_x('Rodoy', 'NOFY', 'ry-wc-city-select'),
		_x('Rost', 'NOFY', 'ry-wc-city-select'),
		_x('Saltdal', 'NOFY', 'ry-wc-city-select'),
		_x('Somna', 'NOFY', 'ry-wc-city-select'),
		_x('Sorfold', 'NOFY', 'ry-wc-city-select'),
		_x('Sortland', 'NOFY', 'ry-wc-city-select'),
		_x('Steigen', 'NOFY', 'ry-wc-city-select'),
		_x('Tjeldsund', 'NOFY', 'ry-wc-city-select'),
		_x('Traena', 'NOFY', 'ry-wc-city-select'),
		_x('Tysfjord', 'NOFY', 'ry-wc-city-select'),
		_x('Vaeroy', 'NOFY', 'ry-wc-city-select'),
		_x('Vagan', 'NOFY', 'ry-wc-city-select'),
		_x('Vefsn', 'NOFY', 'ry-wc-city-select'),
		_x('Vega', 'NOFY', 'ry-wc-city-select'),
		_x('Vestvagoy', 'NOFY', 'ry-wc-city-select'),
		_x('Vevelstad', 'NOFY', 'ry-wc-city-select'),
	],
	'OPFY' => [
		_x('Dovre', 'OPFY', 'ry-wc-city-select'),
		_x('Etnedal', 'OPFY', 'ry-wc-city-select'),
		_x('Gausdal', 'OPFY', 'ry-wc-city-select'),
		_x('Gjovik', 'OPFY', 'ry-wc-city-select'),
		_x('Gran', 'OPFY', 'ry-wc-city-select'),
		_x('Jevnaker', 'OPFY', 'ry-wc-city-select'),
		_x('Lesja', 'OPFY', 'ry-wc-city-select'),
		_x('Lillehammer', 'OPFY', 'ry-wc-city-select'),
		_x('Lom', 'OPFY', 'ry-wc-city-select'),
		_x('Lunner', 'OPFY', 'ry-wc-city-select'),
		_x('Nord-Aurdal', 'OPFY', 'ry-wc-city-select'),
		_x('Nord-Fron', 'OPFY', 'ry-wc-city-select'),
		_x('Nordre Land', 'OPFY', 'ry-wc-city-select'),
		_x('Ostre Toten', 'OPFY', 'ry-wc-city-select'),
		_x('Oyer', 'OPFY', 'ry-wc-city-select'),
		_x('Oystre Slidre', 'OPFY', 'ry-wc-city-select'),
		_x('Ringebu', 'OPFY', 'ry-wc-city-select'),
		_x('Sel', 'OPFY', 'ry-wc-city-select'),
		_x('Skjak', 'OPFY', 'ry-wc-city-select'),
		_x('Sondre Land', 'OPFY', 'ry-wc-city-select'),
		_x('Sor-Aurdal', 'OPFY', 'ry-wc-city-select'),
		_x('Sor-Fron', 'OPFY', 'ry-wc-city-select'),
		_x('Vaga', 'OPFY', 'ry-wc-city-select'),
		_x('Vang', 'OPFY', 'ry-wc-city-select'),
		_x('Vestre Slidre', 'OPFY', 'ry-wc-city-select'),
		_x('Vestre Toten', 'OPFY', 'ry-wc-city-select'),
	],
	'OSFY' => [
		_x('Aremark', 'OSFY', 'ry-wc-city-select'),
		_x('Askim', 'OSFY', 'ry-wc-city-select'),
		_x('Eidsberg', 'OSFY', 'ry-wc-city-select'),
		_x('Fredrikstad', 'OSFY', 'ry-wc-city-select'),
		_x('Halden', 'OSFY', 'ry-wc-city-select'),
		_x('Hobol', 'OSFY', 'ry-wc-city-select'),
		_x('Hvaler', 'OSFY', 'ry-wc-city-select'),
		_x('Marker', 'OSFY', 'ry-wc-city-select'),
		_x('Moss', 'OSFY', 'ry-wc-city-select'),
		_x('Rade', 'OSFY', 'ry-wc-city-select'),
		_x('Rakkestad', 'OSFY', 'ry-wc-city-select'),
		_x('Romskog', 'OSFY', 'ry-wc-city-select'),
		_x('Rygge', 'OSFY', 'ry-wc-city-select'),
		_x('Sarpsborg', 'OSFY', 'ry-wc-city-select'),
		_x('Skiptvet', 'OSFY', 'ry-wc-city-select'),
		_x('Spydeberg', 'OSFY', 'ry-wc-city-select'),
		_x('Trogstad', 'OSFY', 'ry-wc-city-select'),
		_x('Valer', 'OSFY', 'ry-wc-city-select'),
	],
	'ROFY' => [
		_x('Bjerkreim', 'ROFY', 'ry-wc-city-select'),
		_x('Bokn', 'ROFY', 'ry-wc-city-select'),
		_x('Eigersund', 'ROFY', 'ry-wc-city-select'),
		_x('Finnoy', 'ROFY', 'ry-wc-city-select'),
		_x('Forsand', 'ROFY', 'ry-wc-city-select'),
		_x('Gjesdal', 'ROFY', 'ry-wc-city-select'),
		_x('Ha', 'ROFY', 'ry-wc-city-select'),
		_x('Haugesund', 'ROFY', 'ry-wc-city-select'),
		_x('Hjelmeland', 'ROFY', 'ry-wc-city-select'),
		_x('Karmoy', 'ROFY', 'ry-wc-city-select'),
		_x('Klepp', 'ROFY', 'ry-wc-city-select'),
		_x('Kvitsoy', 'ROFY', 'ry-wc-city-select'),
		_x('Lund', 'ROFY', 'ry-wc-city-select'),
		_x('Randaberg', 'ROFY', 'ry-wc-city-select'),
		_x('Rennesoy', 'ROFY', 'ry-wc-city-select'),
		_x('Sandnes', 'ROFY', 'ry-wc-city-select'),
		_x('Sauda', 'ROFY', 'ry-wc-city-select'),
		_x('Sokndal', 'ROFY', 'ry-wc-city-select'),
		_x('Sola', 'ROFY', 'ry-wc-city-select'),
		_x('Stavanger', 'ROFY', 'ry-wc-city-select'),
		_x('Strand', 'ROFY', 'ry-wc-city-select'),
		_x('Suldal', 'ROFY', 'ry-wc-city-select'),
		_x('Time', 'ROFY', 'ry-wc-city-select'),
		_x('Tysvaer', 'ROFY', 'ry-wc-city-select'),
		_x('Utsira', 'ROFY', 'ry-wc-city-select'),
		_x('Vindafjord', 'ROFY', 'ry-wc-city-select'),
	],
	'SOFJFY' => [
		_x('Ardal', 'SOFJFY', 'ry-wc-city-select'),
		_x('Askvoll', 'SOFJFY', 'ry-wc-city-select'),
		_x('Aurland', 'SOFJFY', 'ry-wc-city-select'),
		_x('Balestrand', 'SOFJFY', 'ry-wc-city-select'),
		_x('Bremanger', 'SOFJFY', 'ry-wc-city-select'),
		_x('Eid', 'SOFJFY', 'ry-wc-city-select'),
		_x('Fjaler', 'SOFJFY', 'ry-wc-city-select'),
		_x('Flora', 'SOFJFY', 'ry-wc-city-select'),
		_x('Forde', 'SOFJFY', 'ry-wc-city-select'),
		_x('Gaular', 'SOFJFY', 'ry-wc-city-select'),
		_x('Gloppen', 'SOFJFY', 'ry-wc-city-select'),
		_x('Gulen', 'SOFJFY', 'ry-wc-city-select'),
		_x('Hornindal', 'SOFJFY', 'ry-wc-city-select'),
		_x('Hoyanger', 'SOFJFY', 'ry-wc-city-select'),
		_x('Hyllestad', 'SOFJFY', 'ry-wc-city-select'),
		_x('Jolster', 'SOFJFY', 'ry-wc-city-select'),
		_x('Laerdal', 'SOFJFY', 'ry-wc-city-select'),
		_x('Leikanger', 'SOFJFY', 'ry-wc-city-select'),
		_x('Luster', 'SOFJFY', 'ry-wc-city-select'),
		_x('Naustdal', 'SOFJFY', 'ry-wc-city-select'),
		_x('Selje', 'SOFJFY', 'ry-wc-city-select'),
		_x('Sogndal', 'SOFJFY', 'ry-wc-city-select'),
		_x('Solund', 'SOFJFY', 'ry-wc-city-select'),
		_x('Stryn', 'SOFJFY', 'ry-wc-city-select'),
		_x('Vagsoy', 'SOFJFY', 'ry-wc-city-select'),
		_x('Vik', 'SOFJFY', 'ry-wc-city-select'),
	],
	'TEFY' => [
		_x('Bamble', 'TEFY', 'ry-wc-city-select'),
		_x('Bo', 'TEFY', 'ry-wc-city-select'),
		_x('Drangedal', 'TEFY', 'ry-wc-city-select'),
		_x('Fyresdal', 'TEFY', 'ry-wc-city-select'),
		_x('Hjartdal', 'TEFY', 'ry-wc-city-select'),
		_x('Kragero', 'TEFY', 'ry-wc-city-select'),
		_x('Kviteseid', 'TEFY', 'ry-wc-city-select'),
		_x('Nissedal', 'TEFY', 'ry-wc-city-select'),
		_x('Nome', 'TEFY', 'ry-wc-city-select'),
		_x('Notodden', 'TEFY', 'ry-wc-city-select'),
		_x('Porsgrunn', 'TEFY', 'ry-wc-city-select'),
		_x('Sauherad', 'TEFY', 'ry-wc-city-select'),
		_x('Seljord', 'TEFY', 'ry-wc-city-select'),
		_x('Siljan', 'TEFY', 'ry-wc-city-select'),
		_x('Skien', 'TEFY', 'ry-wc-city-select'),
		_x('Tinn', 'TEFY', 'ry-wc-city-select'),
		_x('Tokke', 'TEFY', 'ry-wc-city-select'),
		_x('Vinje', 'TEFY', 'ry-wc-city-select'),
	],
	'TRFY' => [
		_x('Balsfjord', 'TRFY', 'ry-wc-city-select'),
		_x('Bardu', 'TRFY', 'ry-wc-city-select'),
		_x('Berg', 'TRFY', 'ry-wc-city-select'),
		_x('Dyroy', 'TRFY', 'ry-wc-city-select'),
		_x('Gratangen', 'TRFY', 'ry-wc-city-select'),
		_x('Harstad', 'TRFY', 'ry-wc-city-select'),
		_x('Ibestad', 'TRFY', 'ry-wc-city-select'),
		_x('Kafjord', 'TRFY', 'ry-wc-city-select'),
		_x('Karlsoy', 'TRFY', 'ry-wc-city-select'),
		_x('Kvaefjord', 'TRFY', 'ry-wc-city-select'),
		_x('Kvaenangen', 'TRFY', 'ry-wc-city-select'),
		_x('Lavangen', 'TRFY', 'ry-wc-city-select'),
		_x('Lenvik', 'TRFY', 'ry-wc-city-select'),
		_x('Lyngen', 'TRFY', 'ry-wc-city-select'),
		_x('Malselv', 'TRFY', 'ry-wc-city-select'),
		_x('Nordreisa', 'TRFY', 'ry-wc-city-select'),
		_x('Salangen', 'TRFY', 'ry-wc-city-select'),
		_x('Skanland', 'TRFY', 'ry-wc-city-select'),
		_x('Skjervoy', 'TRFY', 'ry-wc-city-select'),
		_x('Sorreisa', 'TRFY', 'ry-wc-city-select'),
		_x('Storfjord', 'TRFY', 'ry-wc-city-select'),
		_x('Torsken', 'TRFY', 'ry-wc-city-select'),
		_x('Tranoy', 'TRFY', 'ry-wc-city-select'),
		_x('Tromso', 'TRFY', 'ry-wc-city-select'),
	],
	'TR' => [
		_x('Afjord', 'TR', 'ry-wc-city-select'),
		_x('Agdenes', 'TR', 'ry-wc-city-select'),
		_x('Bjugn', 'TR', 'ry-wc-city-select'),
		_x('Flatanger', 'TR', 'ry-wc-city-select'),
		_x('Fosnes', 'TR', 'ry-wc-city-select'),
		_x('Frosta', 'TR', 'ry-wc-city-select'),
		_x('Froya', 'TR', 'ry-wc-city-select'),
		_x('Grong', 'TR', 'ry-wc-city-select'),
		_x('Hemne', 'TR', 'ry-wc-city-select'),
		_x('Hitra', 'TR', 'ry-wc-city-select'),
		_x('Holtalen', 'TR', 'ry-wc-city-select'),
		_x('Hoylandet', 'TR', 'ry-wc-city-select'),
		_x('Inderoy', 'TR', 'ry-wc-city-select'),
		_x('Indre Fosen', 'TR', 'ry-wc-city-select'),
		_x('Klaebu', 'TR', 'ry-wc-city-select'),
		_x('Leka', 'TR', 'ry-wc-city-select'),
		_x('Levanger', 'TR', 'ry-wc-city-select'),
		_x('Lierne', 'TR', 'ry-wc-city-select'),
		_x('Malvik', 'TR', 'ry-wc-city-select'),
		_x('Meldal', 'TR', 'ry-wc-city-select'),
		_x('Melhus', 'TR', 'ry-wc-city-select'),
		_x('Meraker', 'TR', 'ry-wc-city-select'),
		_x('Midtre Gauldal', 'TR', 'ry-wc-city-select'),
		_x('Naeroy', 'TR', 'ry-wc-city-select'),
		_x('Namdalseid', 'TR', 'ry-wc-city-select'),
		_x('Namsos', 'TR', 'ry-wc-city-select'),
		_x('Namsskogan', 'TR', 'ry-wc-city-select'),
		_x('Oppdal', 'TR', 'ry-wc-city-select'),
		_x('Orkdal', 'TR', 'ry-wc-city-select'),
		_x('Orland', 'TR', 'ry-wc-city-select'),
		_x('Osen', 'TR', 'ry-wc-city-select'),
		_x('Overhalla', 'TR', 'ry-wc-city-select'),
		_x('Raarvihke - Royrvik', 'TR', 'ry-wc-city-select'),
		_x('Rennebu', 'TR', 'ry-wc-city-select'),
		_x('Roan', 'TR', 'ry-wc-city-select'),
		_x('Roros', 'TR', 'ry-wc-city-select'),
		_x('Selbu', 'TR', 'ry-wc-city-select'),
		_x('Skaun', 'TR', 'ry-wc-city-select'),
		_x('Snaase - Snasa', 'TR', 'ry-wc-city-select'),
		_x('Snillfjord', 'TR', 'ry-wc-city-select'),
		_x('Steinkjer', 'TR', 'ry-wc-city-select'),
		_x('Stjordal', 'TR', 'ry-wc-city-select'),
		_x('Trondheim', 'TR', 'ry-wc-city-select'),
		_x('Tydal', 'TR', 'ry-wc-city-select'),
		_x('Verdal', 'TR', 'ry-wc-city-select'),
		_x('Verran', 'TR', 'ry-wc-city-select'),
		_x('Vikna', 'TR', 'ry-wc-city-select'),
	],
	'VEFY' => [
		_x('Aseral', 'VEFY', 'ry-wc-city-select'),
		_x('Audnedal', 'VEFY', 'ry-wc-city-select'),
		_x('Farsund', 'VEFY', 'ry-wc-city-select'),
		_x('Flekkefjord', 'VEFY', 'ry-wc-city-select'),
		_x('Haegebostad', 'VEFY', 'ry-wc-city-select'),
		_x('Kristiansand', 'VEFY', 'ry-wc-city-select'),
		_x('Kvinesdal', 'VEFY', 'ry-wc-city-select'),
		_x('Lindesnes', 'VEFY', 'ry-wc-city-select'),
		_x('Lyngdal', 'VEFY', 'ry-wc-city-select'),
		_x('Mandal', 'VEFY', 'ry-wc-city-select'),
		_x('Marnardal', 'VEFY', 'ry-wc-city-select'),
		_x('Sirdal', 'VEFY', 'ry-wc-city-select'),
		_x('Sogne', 'VEFY', 'ry-wc-city-select'),
		_x('Songdalen', 'VEFY', 'ry-wc-city-select'),
		_x('Vennesla', 'VEFY', 'ry-wc-city-select'),
	],
	'VEFY2' => [
		_x('Faerder', 'VEFY2', 'ry-wc-city-select'),
		_x('Holmestrand', 'VEFY2', 'ry-wc-city-select'),
		_x('Horten', 'VEFY2', 'ry-wc-city-select'),
		_x('Larvik', 'VEFY2', 'ry-wc-city-select'),
		_x('Re', 'VEFY2', 'ry-wc-city-select'),
		_x('Sande', 'VEFY2', 'ry-wc-city-select'),
		_x('Sandefjord', 'VEFY2', 'ry-wc-city-select'),
		_x('Svelvik', 'VEFY2', 'ry-wc-city-select'),
		_x('Tonsberg', 'VEFY2', 'ry-wc-city-select'),
	],
	]
];